language: python
python:
  - "3.9"  # You can change this to your preferred version
script:
  - python --version  # Print the Python version to verify
  - pip install -r requirements.txt  # Install dependencies
  - pytest  # Run your tests
